import './App.css';
import Calendar from './Features/Calendar/Calendar';
import EventsLoader from './Features/Events/EventsLoader';
import EventWindow from './Features/Windows/Event/EventWindow';
import DayWindow from './Features/Windows/Day/DayWindow';
import ContactWindow from './Features/Windows/Contact/ContactWindow';
import ContactsLoader from './Features/Contacts/ContactsLoader';
import ImagesWindow from './Features/Windows/Images/ImagesWIndow';
import MenuWindow from './Features/Windows/Menu/MenuWindow';
import AuthProvider from './DB/auth/AuthProvider';
import ImageArrayViewer from './Components/ImageArrayViewer';

/*

  working on
  


  Images
    viwing, editing, moving around, delete etc
    view on hover, circle in event
    Map image too for map pinpoint

  contact
    create new
    search
    view/edit from search
    contact dependents
    events from contacts
    stats

  Shortcuts
    alt+c for new contact with name input focused
    alt+s for search with name box focused
    esc to close top window
    etc

  UI
  Now that functionality is there create a better UI

*/

function App() {
  return (
    <div className="App">
      <AuthProvider>
        <Calendar></Calendar>
        
        <MenuWindow />      
        <DayWindow />
        <EventWindow />
        <ContactWindow />
        <ImagesWindow />
        <ImageArrayViewer />

        <EventsLoader />
        <ContactsLoader />
      </AuthProvider>
    </div>
  );
}

export default App;

/*

  db structure:
  
create table public.images (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  storage_key text null,
  user_id text null,
  bucket text null,
  note text null,
  tags text null,
  item_id text null,
  index text null,
  public_url text null,
  constraint images_pkey primary key (id)
) TABLESPACE pg_default;

  create table public.contacts (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    name text null,
    phone text null,
    email text null,
    facebook text null,
    address text null,
    status text null,
    note text null,
    user_id text null,
    main_image text null,
    constraint contacts_pkey primary key (id)
  ) TABLESPACE pg_default;

  create table public.events (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    title text null,
    note text null,
    date text null,
    status text null,
    contact_id text null,
    start_time text null,
    end_time text null,
    user_id text null,
    constraint events_pkey primary key (id)
) TABLESPACE pg_default;

*/
