import './App.css';
import Calendar from './Features/Calendar/Calendar';
import EventsLoader from './Features/Events/EventsLoader';
import EventWindow from './Features/Windows/Event/EventWindow';
import DayWindow from './Features/Windows/Day/DayWindow';
import ContactWindow from './Features/Windows/Contact/ContactWindow';
import ContactsLoader from './Features/Contacts/ContactsLoader';
import ImagesWindow from './Features/Windows/Images/ImagesWIndow';
import MenuWindow from './Features/Windows/Menu/MenuWindow';

/*

  workingon
  
  events and contacts loading 
  together at same time with existing O(1) jsons to get contact id
  maybe cashing
  understanding the flow and making sure its logical

  Auth provider component
  Data loading checks for user id when loading

  Day notes table

  Images
  uploading multiple
  viwing, editing, moving around, delete etc
  view on hover, circle in event
  Map image too for map pinpoint

  contact dependents

  UI
  Now that functionality is there create a better UI

*/

function App() {
  return (
    <div className="App">
      <Calendar></Calendar>
      
      <MenuWindow />      
      <DayWindow />
      <EventWindow />
      <ContactWindow />
      <ImagesWindow />

      <EventsLoader />
      <ContactsLoader />
    </div>
  );
}

export default App;

/*

  db structure:
  
  images table
  download_url
  storage_url
  user_id
  contact_id

  create table public.contacts (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    name text null,
    phone text null,
    email text null,
    facebook text null,
    address text null,
    status text null,
    note text null,
    user_id text null,
    main_image text null,
    constraint contacts_pkey primary key (id)
  ) TABLESPACE pg_default;

  create table public.events (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    title text null,
    note text null,
    date text null,
    status text null,
    contact_id text null,
    start_time text null,
    end_time text null,
    user_id text null,
    constraint events_pkey primary key (id)
) TABLESPACE pg_default;

*/
